accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView


urlpatterns = [path("login/", LoginView.as_view(), name="login")]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import ReceiptListView


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(null=True)
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render

# Create your views here.

receipts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from receipts.models import Receipt

# Create your views here.
class ReceiptListView(ListView):
    model = Receipt
    template_name = "receipts/list.html"

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <h1>My Receipts</h1>
        <table>
            <thread>
            <tr>    
                <th> Vendor </th>
                <th> Total </th> 
                <th> Tax </th> 
                <th> Date </th> 
                <th> Category </th> 
                <th> Account </th> 
            </tr>
            </thread>
            <tbody>    
               {% for receipt in receipt_list %} 
                <tr>  
                    <td> {{receipt.vendor}} </td>
                    <td> {{receipt.total}} </td> 
                    <td> {{receipt.tax}} </td> 
                    <td> {{receipt.date|date:"m-d-Y"}} </td>  
                    <td> {{receipt.category}} </td> 
                    <td> {{receipt.account}} </td> 
                </tr>
                {% endfor %}
            </tbody>
        </table>




                    
            </tbody>
        </table>    
    </main>
</body>
</html>



{% comment %} <tr> Vendor </tr>
                        <tr>{{vendor.receipt}}</tr>
                    <tr> Total </tr>
                        <tr> {{vendor.total}}</tr>
                    <th>Tax</th>
                        <tr> {{vendor.tax}}</tr>
                    <th>Date</th>
                        <tr> {{vendor.date}}</tr>
                    <th>Category</th>
                        <tr> {{vendor.category}}</tr>
                    <th>Account</th>
                        <tr> {{vendor.account}}</tr> {% endcomment %}